(function(){
const en={
'سيارتي':'My Car','رفيقك لإدارة مركباتك':'Your vehicle management companion','سيارتي - سجل المركبة':'My Car - Vehicle Record','سيارتي · بياناتك محفوظة محلياً على جهازك':'My Car · Your data is stored locally on your device','سيارتي · تقرير خاص بالمركبة المختارة · العملات معروضة دون تحويل':'My Car · Selected vehicle report · Currencies shown without conversion','كل مركباتك في مكان واحد':'All your vehicles in one place','مرآبك الرقمي':'Your digital garage','مرحباً في':'Welcome to','تابع مركباتك وصيانتها ومصاريفها ورحلاتها من لوحة واحدة.':'Track vehicles, maintenance, expenses, and trips from one dashboard.',
'الرئيسية':'Home','الصفحة الرئيسية':'Home','المركبات':'Vehicles','التقارير':'Reports','التذكيرات':'Reminders','التنقل الرئيسي':'Main navigation','الملف الشخصي':'User profile','لوحة القيادة':'Dashboard','كل مركباتك... في مكان واحد':'All your vehicles... in one place','عرض المركبات':'View Vehicles','إجمالي المسافة':'Total Distance','اختصارات ذكية':'Smart Shortcuts','الوصول السريع':'Quick Access','إدارة مركباتك':'Manage your vehicles','السجلات والمواعيد':'Records and schedules','التكاليف والعملات':'Costs and currencies','الطباعة والتصدير':'Print and export','التذكيرات / الإعدادات':'Reminders / Settings','الصيانة القادمة':'Next Maintenance','مرآبك':'Your Garage',
'إضافة مركبة':'Add Vehicle','مركبات':'Vehicles','كم على العدادات':'km on odometers','سجل محفوظ':'Saved records','لا توجد مركبات بعد':'No vehicles yet','أضف مركبتك الأولى للبدء':'Add your first vehicle to begin','فتح الملف':'Open profile','جميع المركبات':'All Vehicles','طباعة سجل المركبة':'Print Vehicle Record','تعديل المركبة':'Edit Vehicle','حذف المركبة':'Delete Vehicle','ملف المركبة':'Vehicle Profile',
'الوقود':'Fuel','اللون':'Color','العداد الحالي':'Current Odometer','آخر تحديث':'Last Updated','تعديل العداد':'Edit Odometer','دون رقم لوحة':'No plate number','كيلومترات الرحلات':'Trip Kilometers','إجمالي المصاريف':'Total Expenses','عمليات الصيانة':'Maintenance Records','عدد الرحلات':'Trip Count','التكلفة لكل كم':'Cost per km','بيانات غير كافية':'Insufficient data',
'الصيانة القادمة':'Next Maintenance','تغيير الفترة':'Change Interval','إضافة صيانة':'Add Maintenance','إضافة مصروف':'Add Expense','إضافة رحلة':'Add Trip','العناية بالمركبة':'Vehicle Care','سجل الصيانة':'Maintenance Log','سجل جديد':'New Record','لا توجد صيانات مسجلة':'No maintenance records','أضف أول سجل صيانة لهذه المركبة':'Add the first maintenance record for this vehicle',
'الصورة المالية':'Financial Overview','المصاريف':'Expenses','مصروف جديد':'New Expense','الإجمالي حسب العملة':'Totals by Currency','لا توجد تكاليف مسجلة':'No costs recorded','لا توجد مصاريف مسجلة':'No expenses recorded','ابدأ بإضافة أول مصروف':'Start by adding an expense','ذاكرة الطريق':'Road Journal','الرحلات':'Trips','رحلة جديدة':'New Trip','جميع الرحلات':'All Trips','القادمة':'Upcoming','السابقة':'Past','لا توجد رحلات هنا':'No trips here','أضف رحلة جديدة لهذه المركبة':'Add a trip for this vehicle',
'معاينة التقرير':'Report Preview','تقرير المركبة / طباعة السجل':'Vehicle Report / Print Record','الأقسام المطلوبة':'Report Sections','معلومات المركبة':'Vehicle Information','الإحصائيات':'Statistics','الفترة الزمنية':'Date Range','جميع السجلات':'All Records','فترة محددة':'Custom Range','من تاريخ':'From Date','إلى تاريخ':'To Date','طباعة / حفظ PDF':'Print / Save PDF','تاريخ إنشاء التقرير':'Report Created','الشركة المصنعة':'Manufacturer','الموديل':'Model','الفئة / الطراز':'Trim / Grade','سنة الصنع':'Model Year','نوع الوقود':'Fuel Type','رقم اللوحة':'Plate Number','آخر تحديث للعداد':'Odometer Last Updated','سجل المصاريف':'Expense Log','سجل الرحلات':'Trip Log','الإحصائيات والصيانة القادمة':'Statistics and Next Maintenance','لا توجد سجلات ضمن الفترة المحددة':'No records in selected date range',
'نسخة احتياطية':'Backup','استعادة نسخة':'Restore Backup','النسخة الاحتياطية':'Backup','استعادة النسخة':'Restore Backup','تأكيد الحذف':'Confirm Deletion','إلغاء':'Cancel','حذف':'Delete','حفظ البيانات':'Save Data','إغلاق':'Close','تعديل السجل':'Edit Record','مرآب سيارتي':'My Car Garage','اسم المركبة (اختياري)':'Vehicle Name (Optional)','اسم المركبة':'Vehicle Name','شركة أخرى':'Other Make','اسم الشركة':'Make Name','موديل آخر':'Other Model','اسم الموديل':'Model Name','بدون فئة':'No Trim','فئة أخرى':'Other Trim','اسم الفئة':'Trim Name','لون آخر':'Other Color','اسم اللون':'Color Name','رقم اللوحة (اختياري)':'Plate Number (Optional)','ملاحظات اختيارية':'Optional notes','ملاحظات':'Notes',
'إعدادات الصيانة القادمة':'Next Maintenance Settings','فترة الصيانة الافتراضية':'Default Maintenance Interval','قراءة العداد الحالية':'Current Odometer Reading','قراءة العداد':'Odometer Reading','التاريخ':'Date','نوع الصيانة':'Maintenance Type','التكلفة':'Cost','العملة':'Currency','الورشة أو الوكالة':'Workshop or Dealer','ملاحظات الصيانة':'Maintenance Notes','التصنيف':'Category','المبلغ':'Amount','نقطة الانطلاق':'Starting Point','الوجهة':'Destination','تاريخ الرحلة':'Trip Date','نوع الرحلة':'Trip Type','عداد البداية':'Start Odometer','عداد النهاية':'End Odometer','تكلفة الرحلة':'Trip Cost','ملاحظات الرحلة':'Trip Notes','مصروفات الرحلة':'Trip Expenses','نوع المصروف':'Expense Type','إجمالي تكلفة الرحلة':'Total Trip Cost','إجمالي المسافة المقطوعة للرحلة':'Total Trip Distance','إجمالي المسافة المقطوعة للرحلة (km)':'Total Trip Distance (km)','إجمالي المسافة':'Total Distance','إجمالي التكلفة':'Total Cost','إضافة مصروف':'Add Expense','حذف المصروف':'Delete Expense',
'تعديل بيانات المركبة':'Edit Vehicle Details','تعديل قراءة العداد':'Edit Odometer Reading','إضافة سجل صيانة':'Add Maintenance Record','تعديل سجل الصيانة':'Edit Maintenance Record','تعديل المصروف':'Edit Expense','تعديل الرحلة':'Edit Trip','تم حفظ البيانات':'Data saved','تم تحديث البيانات':'Data updated','تم الحذف بنجاح':'Deleted successfully','تم تصدير جميع بيانات سيارتي':'All My Car data exported','تمت استعادة جميع المركبات والسجلات':'All vehicles and records restored','الملف غير صالح أو ليس نسخة سيارتي':'Invalid My Car backup file',
'اختر نوع صيانة واحداً على الأقل':'Select at least one maintenance type','اكتب اسم الشركة':'Enter make name','اكتب اسم الموديل':'Enter model name','اكتب اسم الفئة':'Enter trim name','اكتب اسم اللون':'Enter color name','عداد النهاية يجب أن يكون أكبر من عداد البداية':'End odometer must exceed start odometer',
'سيتم حذف مركبة':'Delete vehicle','وجميع سجلاتها المرتبطة نهائياً. لا يمكن التراجع عن ذلك.':'and all linked records permanently. This cannot be undone.','سيتم حذف':'Delete','نهائياً من سجل هذه المركبة.':'permanently from this vehicle record.',
'حان موعد الصيانة':'Maintenance is due','اقترب موعد الصيانة، جهّز موعدك الآن':'Maintenance is approaching; schedule it now','كل شيء على ما يرام':'Everything looks good','تم تجاوز الموعد بمقدار':'Overdue by','كم متبقية':'km remaining','الموعد عند':'Due at','حان موعدها — متجاوزة بمقدار':'Due now — overdue by','متبقي':'Remaining',
'الدينار الكويتي':'Kuwaiti Dinar','دينار كويتي':'Kuwaiti Dinar','الليرة التركية':'Turkish Lira','اليورو':'Euro','الدولار الأمريكي':'US Dollar','الريال السعودي':'Saudi Riyal',
'بنزين':'Gasoline','ديزل':'Diesel','هجين':'Hybrid','كهرباء':'Electric','أخرى':'Other','أبيض':'White','أسود':'Black','فضي':'Silver','رمادي':'Gray','بيج':'Beige','بني':'Brown','أحمر':'Red','أزرق':'Blue','أخضر':'Green','أصفر':'Yellow','برتقالي':'Orange','ذهبي':'Gold','وقود':'Fuel','بقالة / سوبرماركت':'Grocery / Supermarket','مطعم':'Restaurant','فندق':'Hotel','صيانة أو سيرفس':'Maintenance or Service','تكلفة رحلة سابقة':'Previous Trip Cost','مثال: تغيير زيت، فلاتر، إطارات، إصلاح':'e.g. oil change, filters, tires, repair',
'تغيير زيت المحرك':'Engine Oil Change','فلتر الزيت':'Oil Filter','فلتر الديزل':'Diesel Filter','فلتر الهواء':'Air Filter','الإطارات':'Tires','الفرامل':'Brakes','صيانة أخرى':'Other Maintenance','الصيانة':'Maintenance','قطع الغيار':'Spare Parts','التأمين':'Insurance','الرسوم':'Fees','مخالفات':'Fines','مصروف آخر':'Other Expense','داخلية':'Local','سفر':'Travel','برية':'Off-road',
'اللغة':'Language','من':'From','إلى':'To','المسافة':'Distance','الورشة':'Workshop','النوع':'Type','السجلات':'Records','العداد':'Odometer','الاسم':'Name','الملاحظات':'Notes','تعديل':'Edit','صورة المركبة':'Vehicle image','لا توجد تكاليف':'No costs','لا توجد مصاريف':'No expenses','بلا ملاحظات':'No notes','مركبة بدون اسم':'Unnamed Vehicle','اسم مقدم الخدمة':'Service provider name','أدخل عداد النهاية لحساب المسافة':'Enter end odometer to calculate distance','المسافة المحسوبة':'Calculated distance','مثال: لؤلؤي':'e.g. Pearl','مثال: شقران أو الجيب':'e.g. Shagran or The Jeep','صفحة':'Page','سجل':'record','إجمالي':'Total','كم':'km',
'إضافة صورة المركبة':'Add Vehicle Photo','تغيير الصورة':'Change Photo','حذف الصورة':'Delete Photo','تم حفظ صورة المركبة':'Vehicle photo saved','تم حذف الصورة':'Photo deleted','صيغة الصورة غير مدعومة':'Unsupported image format','تعذر قراءة الصورة':'Could not read image'
,'سجّل الدخول للوصول إلى مركباتك':'Sign in to access your vehicles','مرحباً بعودتك':'Welcome Back','اختر طريقة تسجيل الدخول للمتابعة':'Choose a sign-in method to continue','المتابعة بواسطة Google':'Continue with Google','أو بالبريد الإلكتروني':'Or use email','تسجيل الدخول':'Sign In','إنشاء حساب':'Create Account','البريد الإلكتروني':'Email','كلمة المرور':'Password','تسجيل الخروج':'Sign Out','صورة المستخدم':'User avatar'
,'تنزيل النسخة الاحتياطية':'Download backup','استعادة النسخة الاحتياطية':'Restore backup','العملات':'Currencies','الإجمالي النهائي ومحول العملات':'Final Total and Currency Converter','جارٍ تحميل أسعار الصرف…':'Loading exchange rates…','عرض الإجمالي النهائي بعملة':'Show final total in','يتم تحويل إجماليات العملات الأصلية بسعر الصرف الحالي.':'Original-currency totals are converted using the current exchange rate.','المبلغ':'Amount','من عملة':'From currency','إلى عملة':'To currency','تبديل العملات':'Swap currencies','أسعار الصرف بواسطة ExchangeRate-API':'Exchange rates by ExchangeRate-API'
};
const ar=Object.fromEntries(Object.keys(en).map(key=>[key,key]));
window.TRANSLATIONS={ar,en};
})();
