/* كتالوج مستقل عن منطق الواجهة، ويمكن توسيعه بإضافة عناصر فقط. */
window.VEHICLE_CATALOG = Object.freeze({
  makes: {
    'Toyota':['Land Cruiser','Land Cruiser Prado','Land Cruiser 70','Hilux','Tacoma','Tundra','Sequoia','4Runner','Fortuner','Highlander','RAV4','Corolla Cross','Corolla','Camry','Crown','Yaris','Supra'],
    'Lexus':['LX','GX','RX','NX','UX','TX','LBX','RZ','ES','LS','IS','LM','LC'],
    'Nissan':['Patrol','Armada','X-Trail','Pathfinder','Navara','Frontier','X-Terra','Kicks','Qashqai','Altima','Maxima','Sunny','Sentra','Z'],
    'Infiniti':['QX80','QX60','QX55','QX50','Q50'],
    'GMC':['Yukon','Yukon XL','Sierra 1500','Sierra HD','Canyon','Terrain','Acadia','Hummer EV'],
    'Chevrolet':['Tahoe','Suburban','Silverado 1500','Silverado HD','Colorado','Traverse','Captiva','Trailblazer','Equinox','Groove','Malibu','Corvette','Camaro'],
    'Cadillac':['Escalade','Escalade ESV','XT6','XT5','XT4','CT5','CT4','Lyriq','Optiq','Celestiq'],
    'Ford':['Expedition','Explorer','Bronco','Bronco Sport','F-150','F-150 Raptor','F-150 Lightning','Ranger','Maverick','Everest','Mustang','Territory','Taurus'],
    'Lincoln':['Navigator','Aviator','Nautilus','Corsair'],
    'Dodge':['Durango','Charger','Challenger','Hornet'],
    'Jeep':['Wrangler','Grand Cherokee','Gladiator','Compass','Renegade','Wagoneer','Grand Wagoneer'],
    'Chrysler':['300','Pacifica'],
    'RAM':['1500','2500','3500','TRX','ProMaster'],
    'Land Rover':['Range Rover','Range Rover Sport','Range Rover Velar','Range Rover Evoque','Defender','Discovery','Discovery Sport'],
    'Range Rover':['Range Rover','Range Rover Sport','Range Rover Velar','Range Rover Evoque'],
    'BMW':['X1','X2','X3','X4','X5','X6','X7','3 Series','5 Series','7 Series','iX'],
    'Mercedes-Benz':['G-Class','GLS','GLE','GLC','E-Class','S-Class','C-Class','V-Class','EQS'],
    'Audi':['Q3','Q5','Q7','Q8','A3','A4','A6','A8','e-tron GT'],
    'Porsche':['Cayenne','Macan','Panamera','911','Taycan','718'],
    'Volkswagen':['Touareg','Tiguan','Teramont','Golf','Passat','ID.4'],
    'Volvo':['XC90','XC60','XC40','S90','S60','EX30'],
    'Jaguar':['F-Pace','E-Pace','I-Pace','F-Type','XE','XF'],
    'Bentley':['Bentayga','Continental GT','Flying Spur'],
    'Rolls-Royce':['Cullinan','Ghost','Phantom','Spectre'],
    'Ferrari':['Purosangue','Roma','296 GTB','SF90','812'],
    'Lamborghini':['Urus','Revuelto','Huracán'],
    'Maserati':['Levante','Grecale','Ghibli','Quattroporte','MC20','GranTurismo'],
    'Aston Martin':['DBX','DB12','Vantage','Vanquish'],
    'Honda':['CR-V','HR-V','ZR-V','Pilot','Passport','Accord','Civic','City','Odyssey','Prelude'],
    'Acura':['MDX','RDX','TLX','Integra','ZDX'],
    'Hyundai':['Palisade','Santa Fe','Tucson','Creta','Kona','Venue','Sonata','Elantra','Azera','Staria','Ioniq 5','Ioniq 6'],
    'Genesis':['GV80','GV70','GV60','G90','G80','G70'],
    'Kia':['Telluride','Sorento','Sportage','Seltos','Sonet','Carnival','K3','K5','K8','EV3','EV5','EV6','EV9'],
    'Mazda':['CX-90','CX-60','CX-5','CX-30','Mazda 3','Mazda 6','MX-5'],
    'Mitsubishi':['Pajero','Montero Sport','Outlander','Eclipse Cross','ASX','L200'],
    'Subaru':['Outback','Forester','Crosstrek','WRX','BRZ'],
    'Suzuki':['Jimny','Grand Vitara','Fronx','Swift','Dzire'],
    'Isuzu':['D-Max','MU-X'],
    'Great Wall / GWM':['Poer','Poer Sahar','Wingle 5','Wingle 7','King Kong Poer'],
    'Haval':['H9','H6','H6 GT','Dargo','Jolion'],
    'Tank':['Tank 300','Tank 400','Tank 500','Tank 700'],
    'BYD':['Song Plus','Tang','Han','Seal','Seal U','Atto 3','Dolphin','Qin Plus'],
    'Geely':['Monjaro','Coolray','Starray','Emgrand','Geometry C'],
    'Chery':['Tiggo 8 Pro Max','Tiggo 8 Pro','Tiggo 7 Pro','Tiggo 4 Pro','Arrizo 6'],
    'JAC':['J7','JS2','JS3','JS4','JS6','JS6 Pro','JS8','S2','S3','S4','T6','T8','T8 Pro','T9','E30X','M4','RF8'],
    'Jetour':['T2','X90 Plus','X70 Plus','Dashing'],
    'MG':['RX8','HS','ZS','One','MG 5','MG 7','MG 4'],
    'Tesla':['Model S','Model 3','Model X','Model Y','Cybertruck','Roadster']
  },
  trims: {
    'Land Rover|Range Rover':['SE','HSE','Autobiography','SV'],
    'Land Rover|Range Rover Sport':['S','SE','Dynamic SE','Dynamic HSE','Autobiography','SV'],
    'Land Rover|Range Rover Velar':['S','Dynamic SE','Dynamic HSE','Autobiography'],
    'Land Rover|Range Rover Evoque':['S','Dynamic SE','Dynamic HSE','Autobiography'],
    'Land Rover|Defender':['S','X-Dynamic SE','X-Dynamic HSE','X','V8','Octa'],
    'Land Rover|Discovery':['S','Dynamic SE','Dynamic HSE','Metropolitan'],
    'Land Rover|Discovery Sport':['S','Dynamic SE','Dynamic HSE'],
    'GMC|Yukon':['SLE','SLT','AT4','AT4 Ultimate','Denali','Denali Ultimate'],
    'GMC|Yukon XL':['SLE','SLT','AT4','AT4 Ultimate','Denali','Denali Ultimate'],
    'GMC|Sierra 1500':['Pro','SLE','Elevation','SLT','AT4','AT4X','Denali','Denali Ultimate'],
    'GMC|Sierra HD':['Pro','SLE','SLT','AT4','Denali','Denali Ultimate'],
    'GMC|Canyon':['Elevation','AT4','AT4X','Denali'],
    'Toyota|Land Cruiser':['GX','GXR','VXR','GR Sport'],
    'Toyota|Land Cruiser Prado':['TX','TXL','VX','Adventure'],
    'Toyota|Hilux':['S','GL','GLX','Adventure','GR Sport'],
    'Toyota|Land Cruiser 70':['Hardtop','Pickup Single Cab','Pickup Double Cab'],
    'Toyota|Tundra':['SR','SR5','Limited','Platinum','1794 Edition','TRD Pro','Capstone'],
    'Toyota|Tacoma':['SR','SR5','TRD Sport','TRD Off-Road','Limited','Trailhunter','TRD Pro'],
    'Nissan|Patrol':['XE','SE T2','SE Titanium','LE T1','LE Titanium','NISMO'],
    'Ford|F-150':['XL','XLT','Lariat','King Ranch','Platinum','Tremor','Raptor'],
    'Ford|Ranger':['XL','XLT','Wildtrak','Platinum','Raptor'],
    'Jeep|Wrangler':['Sport','Sahara','Rubicon','Rubicon X'],
    'Jeep|Gladiator':['Sport','Willys','Mojave','Rubicon'],
    'RAM|1500':['Tradesman','Big Horn','Rebel','Laramie','Limited'],
    'Great Wall / GWM|Poer':['Commercial','Premium','Platinum'],
    'Isuzu|D-Max':['Single Cab','Space Cab','Crew Cab','LS','X-Terrain'],
    'JAC|T8':['Petrol 4x2 Manual','Diesel 4x4 Manual'],
    'JAC|T8 Pro':['Diesel 4x4 Automatic','Petrol 4x2 Automatic','Petrol 4x4 Automatic']
  }
});
