// Run: node tests/vehicle-add.browser.cjs (Chrome installed). Uses an isolated temporary profile.
﻿const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),{spawn}=require('child_process'),assert=require('assert/strict');
(async()=>{
const root=path.resolve(__dirname,'..'),profile=fs.mkdtempSync(path.join(os.tmpdir(),'sayarti-vehicle-test-'));
const server=http.createServer((req,res)=>{try{const file=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);let body=fs.readFileSync(file);if(file.endsWith('index.html'))body=body.toString().replace(/<script[^>]*src="(?:supabase-config[^" ]*|https:[^"]*|auth[^" ]*)"[^>]*><\/script>/g,'');res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');res.end(body)}catch{res.writeHead(404);res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const child=spawn('C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',['--headless=new','--remote-debugging-port=0','--user-data-dir='+profile,'--no-first-run','--no-default-browser-check','about:blank'],{windowsHide:true,stdio:'ignore'});let ws,call;const errors=[];
try{
const pf=path.join(profile,'DevToolsActivePort');for(let i=0;!fs.existsSync(pf)&&i<100;i++)await new Promise(r=>setTimeout(r,100));const port=fs.readFileSync(pf,'utf8').split('\n')[0],targets=await(await fetch('http://127.0.0.1:'+port+'/json')).json();ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);if(m.method==='Runtime.consoleAPICalled'&&m.params.type==='error')errors.push(JSON.stringify(m.params.args));if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result)}};call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});
const ev=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
await call('Page.enable');await call('Runtime.enable');await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await call('Page.addScriptToEvaluateOnNewDocument',{source:`window.fetch=async()=>({ok:true,json:async()=>({result:'success',rates:Object.fromEntries(['KWD','TRY','EUR','USD','SAR','IQD','QAR','BHD','AED','OMR'].map(x=>[x,1]))})});`});
const wait=async()=>{await new Promise(r=>setTimeout(r,300));for(let i=0;i<100;i++){if(await ev(`document.readyState==='complete'&&!!document.querySelector('#vehicle-list')`))return;await new Promise(r=>setTimeout(r,50))}throw Error('Page timeout')};await call('Page.navigate',{url:'http://127.0.0.1:'+server.address().port+'/'});await wait();
const shaqran={id:'shaqran',name:'شقران',make:'Great Wall / GWM',model:'Poer',trim:'Premium',year:2025,color:'white',fuel:'diesel',plate:'unchanged',image:'',imageUrl:'',odometer:12450,odometerUpdatedAt:'2026-01-01T00:00:00.000Z',serviceInterval:10000,notes:'unchanged',createdAt:'2026-01-01T00:00:00.000Z'};
const fixture={version:3,activeVehicleId:null,vehicles:[shaqran,{...shaqran,id:'existing-second',name:'',make:'',model:'',trim:'',year:0}],maintenance:[{id:'m1',vehicleId:'shaqran',types:['engine_oil'],currency:'KWD',date:'2026-01-01',odometer:12000,cost:10}],expenses:[{id:'e1',vehicleId:'shaqran',category:'fuel',amount:15,currency:'KWD',date:'2026-01-01',receipt:'unchanged'}],trips:[{id:'t1',vehicleId:'shaqran',type:'local',currency:'KWD',date:'2026-01-01',expenses:[],totalCost:0,distanceKm:null}]};await ev(`localStorage.setItem('sayyarati-data-v3',${JSON.stringify(JSON.stringify(fixture))})`);
const reload=async()=>{await call('Page.reload');await wait()};await reload();const state=()=>ev(`JSON.parse(localStorage.getItem('sayyarati-data-v3'))`),click=s=>ev(`document.querySelector(${JSON.stringify(s)}).click()`),set=(n,v)=>ev(`(()=>{const el=document.querySelector('#app-form [name=${n}]');el.value=${JSON.stringify(v)};el.dispatchEvent(new Event('change',{bubbles:true}));return el.value})()`),values=()=>ev(`['make','model','year'].map(n=>document.querySelector('#app-form [name='+n+']').value)`);
const protectedBefore=await state();
const submit=async()=>{assert.equal(await ev(`document.querySelector('#app-form').checkValidity()`),true);await ev(`document.querySelector('#app-form button[type=submit]').click()`);assert.equal(await ev(`document.querySelector('#app-dialog').open`),false)};
const nissanForm=async()=>{await set('make','Nissan');assert.equal(await ev(`document.querySelector('[name=model]').value`),'');await set('model','Patrol');await set('trim','فئة أخرى');await set('customTrim','LE');await set('year','2024')};
assert.equal(await ev(`document.querySelector('[data-id="existing-second"] .model').textContent.includes('Toyota')`),false);
await click('[data-action="edit-vehicle-card"][data-id="existing-second"]');assert.deepEqual(await values(),['','','']);await nissanForm();await submit();await reload();let d=await state();assert.deepEqual([d.vehicles[1].id,d.vehicles[1].make,d.vehicles[1].model,d.vehicles[1].trim,d.vehicles[1].year],['existing-second','Nissan','Patrol','LE',2024]);console.log('PASS: incomplete second vehicle editable through UI; ID retained after reload.');
await click('[data-action="home"]');await click('[data-action="add-vehicle"]');assert.deepEqual(await values(),['','','']);assert.equal(await ev(`document.querySelector('#app-form').checkValidity()`),false);await ev(`document.querySelector('#app-form button[type=submit]').click()`);assert.equal(await ev(`document.querySelector('#vehicle-add-error').hidden`),false);assert.equal((await state()).vehicles.length,2);assert.match(await ev(`document.querySelector('#vehicle-add-error').textContent`),/\u062a\u062d\u0642\u0642/);console.log('PASS: incomplete form shows readable Arabic validation error and creates no vehicle.');await nissanForm();await submit();await reload();d=await state();const nissan=d.vehicles.at(-1);assert.deepEqual([nissan.make,nissan.model,nissan.trim,nissan.year],['Nissan','Patrol','LE',2024]);assert.equal(await ev(`document.querySelector('#vehicle-model').textContent`),'Nissan Patrol LE 2024');console.log('PASS: add Nissan / Patrol / LE / 2024; reload preserves storage and display.');
await click('[data-action="home"]');await click('[data-action="add-vehicle"]');await set('make','Land Rover');await set('model','Range Rover');await set('trim','HSE');await set('year','2016');await submit();await reload();d=await state();assert.deepEqual([d.vehicles.at(-1).make,d.vehicles.at(-1).model,d.vehicles.at(-1).trim,d.vehicles.at(-1).year],['Land Rover','Range Rover','HSE',2016]);assert.equal(await ev(`document.querySelector('#vehicle-model').textContent`),'Land Rover Range Rover HSE 2016');console.log('PASS: add Range Rover / HSE / 2016; reload does not replace it with Toyota.');
await click('[data-action="home"]');await click('[data-action="open-vehicle"][data-id="shaqran"]');assert.equal(await ev(`document.querySelector('#vehicle-name').textContent`),'شقران');await click('[data-action="home"]');await click('[data-action="open-vehicle"][data-id="'+nissan.id+'"]');assert.equal(await ev(`document.querySelector('#vehicle-model').textContent`),'Nissan Patrol LE 2024');d=await state();assert.deepEqual(d.vehicles[0],shaqran);assert.deepEqual(d.maintenance,protectedBefore.maintenance);assert.deepEqual(d.expenses,protectedBefore.expenses);assert.deepEqual(d.trips,protectedBefore.trips);assert.equal(d.vehicles.length,4);console.log('PASS: independent switching; Shaqran fixture unchanged; no vehicle deleted.');
await click('[data-action="home"]');await ev(`document.querySelector('#language-select').value='en';document.querySelector('#language-select').dispatchEvent(new Event('change',{bubbles:true}))`);await click('[data-action="add-vehicle"]');await set('make','Nissan');await set('model','موديل آخر');assert.equal(await ev(`document.querySelector('#custom-model-field').hidden`),false);await set('customModel','Test Model');await set('trim','فئة أخرى');await set('customTrim','Test Trim');await set('year','2016');await submit();d=await state();assert.deepEqual([d.vehicles.at(-1).model,d.vehicles.at(-1).trim],['Test Model','Test Trim']);console.log('PASS: custom model and trim values remain stable in English UI.');console.log('Console errors before fault injection:',errors);assert.deepEqual(errors,[]);
await click('[data-action="home"]');await click('[data-action="add-vehicle"]');await nissanForm();
const beforeFailure=await state();
await ev(`window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='sayyarati-data-v3')throw new DOMException('Storage quota exceeded','QuotaExceededError');return window.originalSetItem.call(this,key,value)};document.querySelector('#app-form button[type=submit]').click()`);
assert.equal(await ev(`document.querySelector('#app-dialog').open`),true);
assert.equal(await ev(`document.querySelector('#vehicle-add-error').hidden`),false);
assert.equal(await ev(`document.querySelector('[name=model]').value`),'Patrol');
assert.deepEqual(await state(),beforeFailure);assert.deepEqual(errors,[]);
console.log('PASS: simulated quota failure keeps form and entries; stored data and activeVehicleId unchanged; no uncaught error.');
await ev(`Storage.prototype.setItem=window.originalSetItem`);await submit();
let retried=await state();assert.equal(retried.vehicles.length,beforeFailure.vehicles.length+1);assert.deepEqual(retried.vehicles.slice(0,-1),beforeFailure.vehicles);assert.equal(retried.activeVehicleId,retried.vehicles.at(-1).id);
await reload();retried=await state();assert.equal(retried.vehicles.length,beforeFailure.vehicles.length+1);assert.deepEqual(retried.vehicles[0],shaqran);assert.deepEqual(retried.maintenance,protectedBefore.maintenance);assert.deepEqual(retried.expenses,protectedBefore.expenses);assert.deepEqual(retried.trips,protectedBefore.trips);assert.deepEqual(errors,[]);
console.log('PASS: retry adds exactly one vehicle and activates it; reload preserves both requested vehicles and all existing records.');
await click('[data-action="home"]');await click('[data-action="add-vehicle"]');await nissanForm();
const originalBytes=await ev(`(async()=>{
 const canvas=document.createElement('canvas');canvas.width=4000;canvas.height=3000;
 const ctx=canvas.getContext('2d'),pixels=ctx.createImageData(4000,3000);let seed=123456;
 for(let i=0;i<pixels.data.length;i+=4){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;pixels.data[i]=seed&255;pixels.data[i+1]=(seed>>>8)&255;pixels.data[i+2]=(seed>>>16)&255;pixels.data[i+3]=255}
 ctx.putImageData(pixels,0,0);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));
 window.largePhoto=new File([blob],'large-photo.png',{type:'image/png'});
 const input=document.querySelector('#form-vehicle-image-input'),transfer=new DataTransfer();transfer.items.add(window.largePhoto);input.files=transfer.files;input.dispatchEvent(new Event('change',{bubbles:true}));return blob.size;
})()`);
assert.ok(originalBytes>25*1024*1024);
const photoReady=async()=>{for(let i=0;i<200;i++){if(await ev(`!document.querySelector('#app-form [type=submit]').disabled`))return;await new Promise(r=>setTimeout(r,50))}throw Error('Photo compression timed out')};
await photoReady();
const prepared=await ev(`document.querySelector('#form-vehicle-image-preview').src`);assert.ok(prepared.startsWith('data:image/jpeg;'));assert.ok(prepared.length<=240*1024);
await submit();await reload();
const withPhoto=await state();assert.equal(withPhoto.vehicles.at(-1).image,prepared);
const visible=await ev(`(()=>{const img=document.querySelector('#vehicle-photo');return !img.hidden&&img.complete&&img.naturalWidth>0&&img.naturalWidth<=1600})()`);assert.equal(visible,true);
assert.deepEqual(withPhoto.vehicles[0],shaqran);assert.deepEqual(withPhoto.expenses,protectedBefore.expenses);assert.deepEqual(withPhoto.trips,protectedBefore.trips);
console.log('PASS: large PNG '+originalBytes+' bytes compressed to JPEG '+prepared.length+' encoded characters; photo visible after save and reload.');
const beforePhotoFailure=await state();
await ev(`(async()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError')};const canvas=document.createElement('canvas');canvas.width=100;canvas.height=100;const blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg'));const dt=new DataTransfer();dt.items.add(new File([blob],'photo.jpeg',{type:'image/jpeg'}));const input=document.querySelector('#vehicle-photo-input');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}))})()`);
for(let i=0;i<100;i++){if(await ev(`document.querySelector('.vehicle-photo [data-image-status]')?.textContent.includes('Could not')`))break;await new Promise(r=>setTimeout(r,50))}
assert.match(await ev(`document.querySelector('.vehicle-photo [data-image-status]').textContent`),/Could not/);assert.deepEqual(await state(),beforePhotoFailure);await ev(`Storage.prototype.setItem=window.originalSetItem`);
await ev(`(()=>{const dt=new DataTransfer();dt.items.add(new File(['invalid'],'photo.heic',{type:'image/heic'}));const input=document.querySelector('#vehicle-photo-input');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}))})()`);
for(let i=0;i<100;i++){if(await ev(`document.querySelector('.vehicle-photo [data-image-status]')?.textContent.includes('HEIC')`))break;await new Promise(r=>setTimeout(r,50))}
assert.match(await ev(`document.querySelector('.vehicle-photo [data-image-status]').textContent`),/HEIC/);assert.deepEqual(await state(),beforePhotoFailure);assert.deepEqual(errors,[]);
console.log('PASS: storage failure and undecodable HEIC show clear errors; existing photo and records retained; zero JS errors.');
console.log('All tests used a temporary Chrome profile; real user storage was not accessed.');
}finally{if(call)await call('Browser.close').catch(()=>{});if(ws)ws.close();child.kill();server.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
